# Generated by Django 5.0.6 on 2024-09-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_user_email_alter_user_passage_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Livro",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("titulo", models.CharField(max_length=100)),
                ("autor", models.CharField(blank=True, max_length=100, null=True)),
                ("editora", models.CharField(blank=True, max_length=100, null=True)),
                ("ano", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
